posts_project/posts/urls.py
from django.urls import path
from .views import (
    post_list_and_create,
    load_post_data_view,
    like_unlike_post,
    post_detail,
    post_detail_data_view,
    delete_post,
    update_post,
    image_upload_view,
)

app_name = "posts"

urlpatterns = [
    path("", post_list_and_create, name="main-board"),
    path("like-unlike/", like_unlike_post, name="like-unlike"),
    path("upload/", image_upload_view, name="image-upload"),
    path("<pk>/", post_detail, name="post-detail"),
    path("<pk>/update/", update_post, name="post-update"),
    path("<pk>/delete/", delete_post, name="post-delete"),
    path("data/<int:num_posts>/", load_post_data_view, name="posts-data"),
    path("<pk>/data/", post_detail_data_view, name="post-detail-data"),
]

posts_project/posts_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls", namespace="posts")),
    path("profiles/", include("profiles.urls", namespace="profiles")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts_project/profiles/urls.py
from django.urls import path
from .views import my_profile_view

app_name = "profiles"

urlpatterns = [
    path("my/", my_profile_view, name="my-profile"),
]

posts_project/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from profiles.models import Profile


class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    liked = models.ManyToManyField(User, blank=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.title)

    @property
    def like_count(self):
        return self.liked.all().count()

    def get_photos(self):
        return self.photo_set.all()

    class Meta:
        ordering = ("-created",)

posts_project/profiles/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    avatar = models.ImageField(default="avatar.png", upload_to="avatars")
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"profile of the user {self.user.username}"

posts_project/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            "title",
            "body",
        )

posts_project/profiles/forms.py
from django import forms
from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            "bio",
            "avatar",
        )

posts_project/posts/views.py
from django.shortcuts import render, redirect
from .models import Post, Photo
from django.http import JsonResponse, HttpResponse
from .forms import PostForm
from profiles.models import Profile
from .utils import action_permission
from django.contrib.auth.decorators import login_required


@login_required
def post_list_and_create(request):
    form = PostForm(request.POST or None)
    if request.is_ajax():
        if form.is_valid():
            author = Profile.objects.get(user=request.user)
            instance = form.save(commit=False)
            instance.author = author
            instance.save()
            return JsonResponse(
                {
                    "title": instance.title,
                    "body": instance.body,
                    "author": instance.author.user.username,
                    "id": instance.id,
                }
            )

    context = {
        "form": form,
    }

    return render(request, "posts/main.html", context)


@login_required
def post_detail(request, pk):
    obj = Post.objects.get(pk=pk)
    form = PostForm()

    context = {
        "obj": obj,
        "form": form,
    }

    return render(request, "posts/detail.html", context)


@login_required
def load_post_data_view(request, num_posts):
    if request.is_ajax():
        visible = 3
        upper = num_posts
        lower = upper - visible
        size = Post.objects.all().count()

        qs = Post.objects.all()
        data = []
        for obj in qs:
            item = {
                "id": obj.id,
                "title": obj.title,
                "body": obj.body,
                "liked": True if request.user in obj.liked.all() else False,
                "count": obj.like_count,
                "author": obj.author.user.username,
            }
            data.append(item)
        return JsonResponse({"data": data[lower:upper], "size": size})


@login_required
def post_detail_data_view(request, pk):
    if request.is_ajax():
        obj = Post.objects.get(pk=pk)
        data = {
            "id": obj.id,
            "title": obj.title,
            "body": obj.body,
            "author": obj.author.user.username,
            "avatar": obj.author.avatar.url,
            "logged_in": request.user.username,
        }
        return JsonResponse({"data": data})
    return redirect("posts:main-board")


@login_required
def like_unlike_post(request):
    if request.is_ajax():
        pk = request.POST.get("pk")
        obj = Post.objects.get(pk=pk)
        if request.user in obj.liked.all():
            liked = False
            obj.liked.remove(request.user)
        else:
            liked = True
            obj.liked.add(request.user)
        return JsonResponse({"liked": liked, "count": obj.like_count})
    return redirect("posts:main-board")


@login_required
@action_permission
def update_post(request, pk):
    obj = Post.objects.get(pk=pk)
    if request.is_ajax():
        new_title = request.POST.get("title")
        new_body = request.POST.get("body")
        obj.title = new_title
        obj.body = new_body
        obj.save()
        return JsonResponse(
            {
                "title": new_title,
                "body": new_body,
            }
        )
    return redirect("posts:main-board")


@login_required
@action_permission
def delete_post(request, pk):
    obj = Post.objects.get(pk=pk)
    if request.is_ajax():
        obj.delete()
        return JsonResponse({"msg": "some message"})
    return redirect("posts:main-board")


@login_required
def image_upload_view(request):
    if request.method == "POST":
        img = request.FILES.get("file")
        new_post_id = request.POST.get("new_post_id")
        post = Post.objects.get(id=new_post_id)
        Photo.objects.create(image=img, post=post)
    return HttpResponse()

posts_project/profiles/views.py
from django.shortcuts import render
from .models import Profile
from .forms import ProfileForm
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required


@login_required
def my_profile_view(request):
    obj = Profile.objects.get(user=request.user)
    form = ProfileForm(request.POST or None, request.FILES or None, instance=obj)
    if request.is_ajax():
        if form.is_valid():
            instance = form.save()
            return JsonResponse(
                {
                    "bio": instance.bio,
                    "avatar": instance.avatar.url,
                    "user": instance.user.username,
                }
            )
    context = {
        "obj": obj,
        "form": form,
    }

    return render(request, "profiles/main.html", context)

posts_project/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- favicon -->
        <link rel="icon" type="image/png" href="{% static 'favicon.ico' %}"/>
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl"
              crossorigin="anonymous">
        <!-- Custom css -->
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <!-- dropzone -->
        <link rel="stylesheet" href="{% static 'dropzone.css' %}">
        <script src="{% static 'dropzone.js' %}" defer></script>
        <!-- Custom js -->
        <script src="{% static 'functions.js' %}" defer></script>
        {% block scripts %}
        {% endblock scripts %}
        <title>read posts |
            {% block title %}
            {% endblock title %}
        </title>
    </head>
    <body>
        {% include "navbar.html" %}
        <div class="container mt-3 mb-3">
            {% block content %}
            {% endblock content %}
        </div>
        <!-- Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
                crossorigin="anonymous"></script>
        <!-- Jquery -->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    </body>
</html>

posts_project/templates/navbar.html
{% url 'posts:main-board' as path_to_home %}
{% url 'profiles:my-profile' as path_to_my_profile %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{path_to_home}}">Posts-proj</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link {% if request.path == path_to_home %}active{% endif %}" aria-current="page" href="{{path_to_home}}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == path_to_my_profile %}active{% endif %}" href="{{path_to_my_profile}}">My Profile</a>
        </li>
      </ul>
    </div>
  </div>
</nav>